import type { Guide } from '../types'

export const guide: Guide = {
  slug: 'old-vs-new-tax-regime',
  cluster: 'tax-saving',
  title: 'Old vs New Tax Regime FY 2025-26: Which Saves More Tax?',
  h1: 'Old vs New Tax Regime FY 2025-26 (AY 2026-27): Which Saves More Tax?',
  metaTitle: 'Old vs New Tax Regime FY 2025-26: Which Saves More?',
  metaDescription:
    'Old vs new regime slabs for FY 2025-26 with worked examples at ₹8L, ₹12.75L, ₹18L and ₹30L, break-even deductions, who picks which, and switching rules.',
  keywords: [
    'old vs new tax regime',
    'new tax regime slabs 2025-26',
    'which tax regime is better',
    'new tax regime deductions',
    'old tax regime vs new tax regime calculator',
    'tax regime break even',
    '87a rebate 12 lakh',
    'switch tax regime',
    'income tax slab fy 2025-26',
  ],
  excerpt:
    'The new regime is the default and tax-free up to ₹12.75 lakh of salary. This guide shows exactly how much in deductions you need before the old regime wins, with worked examples at four salary levels.',
  datePublished: '2026-09-06',
  dateModified: '2026-09-06',
  readMinutes: 12,
  sections: [
    {
      type: 'key-takeaways',
      items: [
        'Under the new regime, salary up to ₹12.75 lakh attracts zero tax for FY 2025-26 because of the ₹75,000 standard deduction and the ₹60,000 rebate under section 87A. The old regime cannot match this without ₹7.75 lakh of deductions.',
        'For salaries above ₹24.75 lakh, the old regime wins only if your deductions beyond the standard deduction exceed ₹8 lakh. Between ₹15 lakh and ₹20 lakh the break-even is roughly ₹5.4 lakh to ₹7.1 lakh.',
        'The most common way to cross the break-even is a large HRA exemption plus ₹2 lakh of home loan interest plus a full 80C. Without HRA or a home loan, the new regime almost always wins.',
        'Salaried taxpayers can switch every year, but only in a return filed by the due date. Taxpayers with business income get one lifetime switch out of the new regime.',
      ],
    },
    {
      type: 'stat-grid',
      stats: [
        { label: 'Tax-free salary, new regime', value: '₹12.75 lakh', note: 'Rebate ₹60,000 up to ₹12 lakh taxable' },
        { label: 'Standard deduction', value: '₹75,000', note: '₹50,000 under the old regime' },
        { label: 'Break-even above ₹24.75 lakh', value: '₹8 lakh', note: 'Deductions needed beyond standard deduction' },
        { label: 'Top slab starts at', value: '₹24 lakh', note: '₹10 lakh under the old regime' },
      ],
    },
    {
      type: 'tool-card',
      calculatorSlug: 'income-tax',
      text: 'Enter your salary and deductions once and see both regimes side by side, including 87A rebate, marginal relief, surcharge and cess.',
    },
    { type: 'heading', text: 'Slabs for FY 2025-26 under both regimes', id: 'slabs' },
    {
      type: 'paragraph',
      text: 'Budget 2025 rewrote the new regime slabs and raised the rebate threshold. The old regime slabs have not changed since 2014. The tables below apply to income earned between 1 April 2025 and 31 March 2026, which you report in AY 2026-27.',
    },
    {
      type: 'table',
      head: ['Taxable income', 'New regime rate', 'Tax at top of slab (cumulative)'],
      rows: [
        ['Up to ₹4,00,000', '0%', '₹0'],
        ['₹4,00,001 to ₹8,00,000', '5%', '₹20,000'],
        ['₹8,00,001 to ₹12,00,000', '10%', '₹60,000'],
        ['₹12,00,001 to ₹16,00,000', '15%', '₹1,20,000'],
        ['₹16,00,001 to ₹20,00,000', '20%', '₹2,00,000'],
        ['₹20,00,001 to ₹24,00,000', '25%', '₹3,00,000'],
        ['Above ₹24,00,000', '30%', '₹3,00,000 plus 30% of excess'],
      ],
      caption: 'New regime under section 115BAC. Rebate u/s 87A up to ₹60,000 if taxable income is ₹12 lakh or less, with marginal relief just above.',
    },
    {
      type: 'table',
      head: ['Taxable income', 'Old regime rate (below 60)', 'Tax at top of slab (cumulative)'],
      rows: [
        ['Up to ₹2,50,000', '0%', '₹0'],
        ['₹2,50,001 to ₹5,00,000', '5%', '₹12,500'],
        ['₹5,00,001 to ₹10,00,000', '20%', '₹1,12,500'],
        ['Above ₹10,00,000', '30%', '₹1,12,500 plus 30% of excess'],
      ],
      caption: 'Old regime. Exemption limit is ₹3 lakh for senior citizens and ₹5 lakh for those aged 80 or more. Rebate u/s 87A up to ₹12,500 if taxable income is ₹5 lakh or less.',
    },
    {
      type: 'paragraph',
      text: 'Health and education cess of 4% applies on the tax under both regimes. Surcharge starts above ₹50 lakh, and is capped at 25% under the new regime against 37% under the old regime, which matters only for very high incomes.',
    },
    { type: 'heading', text: 'What you can and cannot claim in each regime', id: 'deductions-allowed' },
    {
      type: 'table',
      head: ['Deduction or exemption', 'Old regime', 'New regime'],
      rows: [
        ['Standard deduction on salary', '₹50,000', '₹75,000'],
        ['HRA exemption u/s 10(13A)', 'Yes', 'No'],
        ['LTA exemption', 'Yes', 'No'],
        ['Section 80C (PF, PPF, ELSS, LIC, tuition, home loan principal)', 'Up to ₹1,50,000', 'No'],
        ['Section 80CCD(1B) own NPS contribution', 'Up to ₹50,000', 'No'],
        ['Section 80CCD(2) employer NPS contribution', 'Up to 10% of basic plus DA', 'Up to 14% of basic plus DA'],
        ['Section 80D health insurance', '₹25,000; ₹50,000 for senior citizens, separately for parents', 'No'],
        ['Section 24(b) home loan interest, self-occupied', 'Up to ₹2,00,000', 'No'],
        ['Section 24(b) interest on let-out property', 'Yes, loss set-off capped at ₹2 lakh', 'Yes, but no set-off of loss against salary'],
        ['Section 80TTA / 80TTB savings interest', '₹10,000 / ₹50,000', 'No'],
        ['Section 80G donations', 'Yes', 'No'],
        ['Section 80E education loan interest', 'Yes', 'No'],
        ['Professional tax deduction', 'Yes', 'No'],
        ['Family pension deduction', '₹15,000', '₹25,000'],
      ],
    },
    { type: 'heading', text: 'Worked example 1: salary ₹8 lakh', id: 'example-8-lakh' },
    {
      type: 'paragraph',
      text: 'At ₹8 lakh the new regime already produces nil tax, so the question is whether the old regime can also reach nil. It can, but only with ₹2.5 lakh of deductions beyond the standard deduction, which typically means a full 80C plus a sizeable HRA claim.',
    },
    {
      type: 'example',
      title: 'Salary ₹8,00,000: new regime',
      lines: [
        { label: 'Gross salary', value: '₹8,00,000' },
        { label: 'Less standard deduction', value: '₹75,000' },
        { label: 'Taxable income', value: '₹7,25,000' },
        { label: 'Tax (5% on ₹3,25,000)', value: '₹16,250' },
        { label: 'Less rebate u/s 87A', value: '₹16,250' },
        { label: 'Tax payable', value: '₹0', strong: true },
      ],
    },
    {
      type: 'example',
      title: 'Salary ₹8,00,000: old regime with 80C ₹1.5 lakh and 80D ₹25,000',
      lines: [
        { label: 'Gross salary', value: '₹8,00,000' },
        { label: 'Less standard deduction', value: '₹50,000' },
        { label: 'Less 80C and 80D', value: '₹1,75,000' },
        { label: 'Taxable income', value: '₹5,75,000' },
        { label: 'Tax (₹12,500 plus 20% on ₹75,000)', value: '₹27,500' },
        { label: 'Add cess 4%', value: '₹1,100' },
        { label: 'Tax payable', value: '₹28,600', strong: true },
      ],
    },
    {
      type: 'callout',
      tone: 'info',
      title: 'Verdict at ₹8 lakh',
      text: 'New regime, unless your deductions beyond the standard deduction reach ₹2.5 lakh, at which point both regimes give nil tax and the new regime is still simpler.',
    },
    { type: 'heading', text: 'Worked example 2: salary ₹12.75 lakh', id: 'example-12-75-lakh' },
    {
      type: 'paragraph',
      text: 'This is the headline number from Budget 2025. Salary of ₹12.75 lakh becomes taxable income of exactly ₹12 lakh after the standard deduction, and the ₹60,000 rebate wipes out the ₹60,000 of slab tax. The old regime needs ₹7.25 lakh of deductions beyond its ₹50,000 standard deduction to reach the ₹5 lakh rebate threshold, which is not realistic for most employees.',
    },
    {
      type: 'example',
      title: 'Salary ₹12,75,000: new vs old (old with 80C, 80D, 80CCD(1B) and ₹2 lakh home loan interest)',
      lines: [
        { label: 'New regime taxable income', value: '₹12,00,000' },
        { label: 'New regime tax after 87A rebate', value: '₹0', strong: true },
        { label: 'Old regime deductions (₹50,000 + ₹1,50,000 + ₹25,000 + ₹50,000 + ₹2,00,000)', value: '₹4,75,000' },
        { label: 'Old regime taxable income', value: '₹8,00,000' },
        { label: 'Old regime tax (₹12,500 plus 20% on ₹3,00,000)', value: '₹72,500' },
        { label: 'Old regime tax with 4% cess', value: '₹75,400', strong: true },
      ],
    },
    {
      type: 'callout',
      tone: 'warning',
      title: 'Marginal relief just above ₹12 lakh',
      text: 'If taxable income is ₹12,10,000, slab tax is ₹61,500 but marginal relief limits the tax to ₹10,000, the amount by which income exceeds ₹12 lakh. Relief tapers off around ₹12.70 lakh of taxable income, after which full slab tax applies.',
    },
    { type: 'heading', text: 'Worked example 3: salary ₹18 lakh', id: 'example-18-lakh' },
    {
      type: 'paragraph',
      text: 'At ₹18 lakh, the new regime charges ₹1,45,000 before cess. For the old regime to match this, taxable income must fall to about ₹11.08 lakh, which requires ₹6.42 lakh of deductions beyond the standard deduction. A metro employee paying high rent with a home loan on a second city property can get there; most cannot.',
    },
    {
      type: 'example',
      title: 'Salary ₹18,00,000: new regime',
      lines: [
        { label: 'Taxable income after ₹75,000 standard deduction', value: '₹17,25,000' },
        { label: 'Tax up to ₹16 lakh', value: '₹1,20,000' },
        { label: 'Tax at 20% on ₹1,25,000', value: '₹25,000' },
        { label: 'Total tax', value: '₹1,45,000' },
        { label: 'Add cess 4%', value: '₹5,800' },
        { label: 'Tax payable', value: '₹1,50,800', strong: true },
      ],
    },
    {
      type: 'example',
      title: 'Salary ₹18,00,000: old regime with ₹4.25 lakh of deductions',
      lines: [
        { label: 'Deductions: SD ₹50,000, 80C ₹1,50,000, 80D ₹25,000, 80CCD(1B) ₹50,000, 24(b) ₹2,00,000', value: '₹4,75,000' },
        { label: 'Taxable income', value: '₹13,25,000' },
        { label: 'Tax up to ₹10 lakh', value: '₹1,12,500' },
        { label: 'Tax at 30% on ₹3,25,000', value: '₹97,500' },
        { label: 'Total tax', value: '₹2,10,000' },
        { label: 'Add cess 4%', value: '₹8,400' },
        { label: 'Tax payable', value: '₹2,18,400', strong: true },
      ],
    },
    {
      type: 'paragraph',
      text: 'Even with every common deduction maxed out, the old regime costs ₹67,600 more at this salary. Add an HRA exemption of ₹2.2 lakh, taking deductions to ₹6.45 lakh, and the old regime pulls ahead by about ₹1,000; a smaller HRA leaves the new regime on top.',
    },
    { type: 'heading', text: 'Worked example 4: salary ₹30 lakh', id: 'example-30-lakh' },
    {
      type: 'paragraph',
      text: 'At ₹30 lakh both regimes tax the top rupee at 30%, so the comparison reduces to a fixed number: the old regime needs deductions of ₹8 lakh beyond the standard deduction to break even. This holds for every salary above ₹24.75 lakh until surcharge enters at ₹50 lakh.',
    },
    {
      type: 'example',
      title: 'Salary ₹30,00,000: new regime',
      lines: [
        { label: 'Taxable income after ₹75,000 standard deduction', value: '₹29,25,000' },
        { label: 'Tax up to ₹24 lakh', value: '₹3,00,000' },
        { label: 'Tax at 30% on ₹5,25,000', value: '₹1,57,500' },
        { label: 'Total tax', value: '₹4,57,500' },
        { label: 'Add cess 4%', value: '₹18,300' },
        { label: 'Tax payable', value: '₹4,75,800', strong: true },
      ],
    },
    {
      type: 'example',
      title: 'Salary ₹30,00,000: old regime with ₹8 lakh of deductions (break-even)',
      lines: [
        { label: 'Standard deduction', value: '₹50,000' },
        { label: 'HRA exemption, 80C, 80D, 80CCD(1B), 24(b) and others', value: '₹8,00,000' },
        { label: 'Taxable income', value: '₹21,50,000' },
        { label: 'Tax (₹1,12,500 plus 30% on ₹11,50,000)', value: '₹4,57,500' },
        { label: 'Add cess 4%', value: '₹18,300' },
        { label: 'Tax payable', value: '₹4,75,800', strong: true },
      ],
    },
    { type: 'heading', text: 'Break-even deductions at every salary level', id: 'break-even-table' },
    {
      type: 'paragraph',
      text: 'The table shows the deductions, over and above the standard deduction, that the old regime needs before it beats the new regime. If your HRA exemption, 80C, 80D, NPS, home loan interest and other claims add up to more than this figure, choose the old regime.',
    },
    {
      type: 'table',
      head: ['Gross salary', 'New regime tax (with cess)', 'Old regime break-even deductions (beyond SD)', 'Likely winner'],
      rows: [
        ['₹8,00,000', '₹0', '₹2,50,000', 'New'],
        ['₹10,00,000', '₹0', '₹4,50,000', 'New'],
        ['₹12,75,000', '₹0', '₹7,25,000', 'New'],
        ['₹15,00,000', '₹97,500', '₹5,43,750', 'New, unless high HRA'],
        ['₹18,00,000', '₹1,50,800', '₹6,41,667', 'New, unless high HRA plus home loan'],
        ['₹20,00,000', '₹1,92,400', '₹7,08,333', 'Depends on HRA'],
        ['₹25,00,000 and above', '₹3,19,800 at ₹25 lakh', '₹8,00,000', 'Old only with very large HRA and loan interest'],
      ],
      caption: 'Break-even computed on FY 2025-26 slabs. Deductions exclude the standard deduction, which is built into both columns.',
    },
    {
      type: 'service-card',
      serviceSlug: 'itr-salaried',
      text: 'Every salaried return we file includes a side-by-side regime computation on your actual Form 16, rent and investment numbers. You approve the better one before we file. From ₹499.',
    },
    { type: 'heading', text: 'Who should pick which regime', id: 'who-should-pick' },
    {
      type: 'list',
      items: [
        'Salary up to ₹12.75 lakh with no other income: new regime, no exceptions worth the paperwork.',
        'Renting in Delhi, Mumbai, Kolkata or Chennai with rent above ₹25,000 a month, plus a home loan and full 80C: run the numbers; the old regime often wins from ₹15 lakh upwards.',
        'Own house, no rent, no home loan: new regime at almost every salary, because 80C, 80D and NPS alone rarely exceed ₹2.25 lakh.',
        'Senior citizens with interest income: the old regime offers ₹50,000 under 80TTB and ₹50,000 under 80D, but the new regime slabs are wider. Above ₹7 lakh of income the new regime usually still wins.',
        'Employer NPS contribution: the new regime allows 14% of basic plus DA under 80CCD(2) against 10% in the old regime, which tilts the comparison further towards the new regime for those with NPS in their CTC.',
        'Business owners and professionals: the switch is once in a lifetime, so choose carefully and think about future years, not just this one.',
      ],
    },
    { type: 'heading', text: 'Rules for switching between regimes', id: 'switching-rules' },
    {
      type: 'paragraph',
      text: 'The new regime is the default under section 115BAC for everyone from FY 2023-24 onwards. Choosing the old regime is an opt-out, and the mechanics differ by type of income.',
    },
    {
      type: 'table',
      head: ['Taxpayer', 'How to opt for the old regime', 'Can switch back?'],
      rows: [
        ['Salaried, no business income', 'Tick the opt-out in the ITR filed by 31 July 2026; no separate form', 'Yes, freely every year'],
        ['Business or professional income', 'File Form 10-IEA before the due date of the return', 'Only once: after returning to the new regime you cannot opt out again'],
        ['Belated return filer (no business income)', 'Not possible; belated returns are assessed under the new regime', 'Next year, if filed on time'],
      ],
    },
    {
      type: 'callout',
      tone: 'info',
      title: 'Your employer choice is not binding',
      text: 'The regime you declared to your employer for TDS only affects the tax deducted during the year. In the return you can pick the other regime, and any excess TDS comes back as a refund.',
    },
    { type: 'heading', text: 'What to do next', id: 'what-to-do-next' },
    {
      type: 'paragraph',
      text: 'Add up your HRA exemption, 80C, 80D, NPS and home loan interest for FY 2025-26 and compare the total with the break-even figure for your salary. If it is below the figure, file under the new regime and stop collecting investment proofs. If it is above, file under the old regime by the due date and keep the proofs for six years. Either way, run the income tax calculator before submitting.',
    },
  ],
  faqs: [
    {
      q: 'Is income up to ₹12 lakh tax-free in the new regime for FY 2025-26?',
      a: 'Yes for taxable income up to ₹12 lakh, which means gross salary up to ₹12.75 lakh after the ₹75,000 standard deduction. The rebate under section 87A is ₹60,000, exactly the slab tax at ₹12 lakh.',
    },
    {
      q: 'How much deduction is needed for the old regime to be better than the new regime?',
      a: 'About ₹8 lakh beyond the standard deduction for salaries above ₹24.75 lakh, roughly ₹6.4 lakh at ₹18 lakh, and ₹5.4 lakh at ₹15 lakh. Below ₹12.75 lakh the new regime is already at nil tax.',
    },
    {
      q: 'Can I claim HRA in the new tax regime?',
      a: 'No. HRA exemption under section 10(13A) is available only in the old regime. The new regime allows the standard deduction, employer NPS contribution under 80CCD(2) and a few other items.',
    },
    {
      q: 'Which deductions are allowed in the new tax regime?',
      a: 'Standard deduction of ₹75,000, employer NPS contribution up to 14% of basic plus DA under 80CCD(2), family pension deduction up to ₹25,000, interest on a let-out property under 24(b) without set-off against salary, and deductions for Agniveer Corpus Fund under 80CCH.',
    },
    {
      q: 'Can I switch from the new regime to the old regime every year?',
      a: 'Yes if you have no business or professional income, by opting out in a return filed by the due date. Taxpayers with business income can switch out of the new regime only once in a lifetime using Form 10-IEA.',
    },
    {
      q: 'What is marginal relief under the new regime?',
      a: 'When taxable income slightly exceeds ₹12 lakh, tax is limited to the amount by which income exceeds ₹12 lakh. At ₹12,10,000 the tax is ₹10,000 instead of ₹61,500. Relief fades out at about ₹12.70 lakh.',
    },
    {
      q: 'Is the old tax regime being removed?',
      a: 'No announcement has removed it. The Income-tax Act 2025, effective from 1 April 2026, retains both regimes with the new regime as the default. Budget changes are announced each February.',
    },
    {
      q: 'Does the ₹75,000 standard deduction apply to pensioners?',
      a: 'Yes. Pension from a former employer is taxed as salary, so pensioners get ₹75,000 under the new regime and ₹50,000 under the old regime. Family pension gets a separate deduction under other sources.',
    },
    {
      q: 'What tax regime should a person with ₹20 lakh salary choose?',
      a: 'The new regime unless deductions beyond the standard deduction exceed about ₹7.08 lakh. New regime tax at ₹20 lakh is ₹1,92,400 including cess. That level of deductions usually needs a large HRA exemption plus ₹2 lakh of home loan interest plus a full 80C.',
    },
  ],
  relatedServiceSlug: 'itr-salaried',
  relatedGuides: ['hra-exemption', 'itr-filing-guide-ay-2026-27', 'income-tax-act-2025-what-changes'],
  relatedCalculators: ['income-tax', 'hra'],
}
